version: '3.5'

services:
    ubuntu:
        build:
            context: .
            dockerfile: ubuntu.dockerfile
        container_name: ubuntu
        ports:
            - 8080:80
            - "67:67/udp"
            - 4005:4005
            - 2068:68
            - 2021:21
            - 3307:3306
        volumes:
            - ./:/var/www/html/api
        cap_add:
            - NET_ADMIN
        networks:
            kali-app-network:
                ipv4_address: 10.0.0.3
    
    mongo:
        image: mongo:latest
        restart: always
        container_name: mongo
        ports:
            - 27031:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
        volumes:
            - ./:/var/www/html
        networks:
            kali-app-network:
                ipv4_address: 10.0.0.13

networks:
  kali-app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "10.0.0.0/16"  # Changed to a more standard Docker subnet